### PR TITLE
Fix `ff_starters()` for multi-week playoff ESPN leagues

### LINKED ISSUE #421: ESPN Player Scores for Multi-Week Playoffs
**Describe the bug**
`ff_starters.espn_conn()` fails when trying to retrieve scores for a week involved in a multi-round playoff format. (FWIW I'd be happy to submit a PR to solve this!)

**Reprex**
Please provide a short, reproducible example of the code you are trying to run. 
For more on reprexes, check out https://reprex.tidyverse.org

```r
library(ffscrapr)
conn <- espn_connect(
  season = 2022,
  league_id = 899513,
  espn_s2 = Sys.getenv('FF_ESPN_S2'),
  swid = Sys.getenv('FF_SWID')
)
## Note the failure at index 16, the second week of the first round of my league's playoffs.
##   4 teams, 2 week rounds, starting with weeks 15 and 16, with champs in weeks 17 and 18.
starters <- ff_starters(conn)
#> Error in `map()`:
#> ℹ In index: 16.
#> Caused by error in `tidyr::hoist()`:
#> ! `.data[[.col]]` must be a list, not a logical vector.
#> Backtrace:
#>      ▆
#>   1. ├─ffscrapr::ff_starters(conn)
#>   2. ├─ffscrapr:::ff_starters.espn_conn(conn)
#>   3. │ ├─... %>% ...
#>   4. │ └─purrr::map_dfr(run_weeks, .espn_week_starter, conn)
#>   5. │   └─purrr::map(.x, .f, ...)
#>   6. │     └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>   7. │       ├─purrr:::with_indexed_errors(...)
#>   8. │       │ └─base::withCallingHandlers(...)
#>   9. │       ├─purrr:::call_with_cleanup(...)
#>  10. │       └─ffscrapr (local) .f(.x[[i]], ...)
#>  11. │         └─... %>% ...
#>  12. ├─dplyr::select(...)
#>  13. ├─dplyr::left_join(...)
#>  14. ├─dplyr::arrange(., .data$week, .data$franchise_id, .data$lineup_id)
#>  15. ├─dplyr::mutate(...)
#>  16. ├─dplyr::mutate(...)
#>  17. ├─tidyr::hoist(...)
#>  18. │ └─tidyr:::check_data_frame(.data)
#>  19. │   └─base::is.data.frame(x)
#>  20. ├─dplyr::select(., -"player_data")
#>  21. ├─tidyr::hoist(...)
#>  22. │ └─tidyr:::check_data_frame(.data)
#>  23. │   └─base::is.data.frame(x)
#>  24. ├─tidyr::hoist(...)
#>  25. │ └─tidyr:::check_data_frame(.data)
#>  26. │   └─base::is.data.frame(x)
#>  27. ├─tidyr::unnest_longer(., "entries")
#>  28. │ └─tidyr:::check_data_frame(data)
#>  29. │   └─base::is.data.frame(x)
#>  30. ├─tidyr::hoist(...)
#>  31. │ └─vctrs::vec_check_list(x, arg = ".data[[.col]]")
#>  32. │   └─vctrs::obj_check_list(x, ..., arg = arg, call = call)
#>  33. └─vctrs:::stop_non_list_type(x, y, z)
#>  34.   └─cli::cli_abort(...)
#>  35.     └─rlang::abort(...)
```
**Expected behavior**
At week 16, the function should return player scores for just week 16.

**Session information**
Please copy the output of `ffscrapr::ffverse_sitrep()` into the box below.
```r
> ffscrapr::ffverse_sitrep()
── System Info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
• R version 4.2.0 (2022-04-22 ucrt) • Running under: Windows 10 x64 (build 22621)
── Package Status ──────────────────────────────────────────────────────────────────────────────────────────────────────────
      package installed  cran      dev   behind
1    ffscrapr  1.4.8.14 1.4.8 1.4.8.14         
2 ffsimulator     1.2.0 1.2.3 1.2.3.01 cran;dev
── Package Options ─────────────────────────────────────────────────────────────────────────────────────────────────────────
• No options set for above packages
── Package Dependencies ────────────────────────────────────────────────────────────────────────────────────────────────────
• askpass    (1.1)     • lifecycle  (1.0.3)   • stringr    (1.5.0)  
• assertthat (0.2.1)   • magrittr   (2.0.3)   • sys        (3.4.2)  
• backports  (1.4.1)   • memoise    (2.0.1)   • tibble     (3.2.1)  
• cachem     (1.0.6)   • mime       (0.12)    • tidyr      (1.3.0)  
• checkmate  (2.1.0)   • nflreadr   (1.4.0)   • tidyselect (1.2.0)  
• cli        (3.6.1)   • openssl    (2.1.0)   • tidytable  (0.8.0)  
• cpp11      (0.4.6)   • pillar     (1.9.0)   • utf8       (1.2.3)  
• curl       (5.0.2)   • pkgconfig  (2.0.3)   • vctrs      (0.6.3)  
• data.table (1.14.8)  • purrr      (1.0.2)   • withr      (2.5.0)  
• dplyr      (1.1.2)   • R6         (2.5.1)   • graphics   (4.2.0)  
• fansi      (1.0.4)   • rappdirs   (0.3.3)   • grDevices  (4.2.0)  
• fastmap    (1.1.0)   • ratelimitr (0.4.1)   • methods    (4.2.0)  
• generics   (0.1.3)   • Rglpk      (0.6-4)   • stats      (4.2.0)  
• glue       (1.6.2)   • rlang      (1.1.1)   • tools      (4.2.0)  
• httr       (1.4.7)   • slam       (0.1-50)  • utils      (4.2.0)  
• jsonlite   (1.8.7)   • stringi    (1.7.12)    
── Not Installed ───────────────────────────────────────────────────────────────────────────────────────────────────────────
• ffpros        ()
• ffopportunity ()
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Screenshots**
image

**Additional context**
`.espn_week_starter()` assumes that `scoringPeriodId == matchupPeriodiId`. i think we can use `settings.scheduleSettings.matchupPeriods` to identify the mapping between scoring and matchup periods, then accomodate for the difference [here](https://github.com/ffverse/ffscrapr/blob/94a72b087c520f1f4a0ec0c55fea813903817ecb/R/espn_starters.R#L94-L102).

### PR DESCRIPTION
**Pull request by tonyelhabr**
Fixes #421.

```r
packageVersion("ffscrapr")
#> [1] '1.4.8.15'
conn22 <- ffscrapr::espn_connect(
  season = 2022,
  league_id = 899513
)

## previously, this would error at index 16 (NFL week 16, second week of 1st round of playoffs)
starters22 <- ffscrapr::ff_starters(conn22, weeks = 1:18)
str(starters22, max.level = 1)
#> tibble [3,495 × 12] (S3: tbl_df/tbl/data.frame)

conn23 <- ffscrapr::espn_connect(
  season = 2023,
  league_id = 899513
)

## nothing broken for this year (no playoffs started)
starters23 <- ffscrapr::ff_starters(conn23, weeks = 1:18)
str(starters23, max.level = 1)
#> tibble [1,999 × 12] (S3: tbl_df/tbl/data.frame)
```

### CODE REVIEW

File: R/espn_starters.R [hunk 1]
```diff
@@ -67,14 +86,7 @@ ff_starters.espn_conn <- function(conn, weeks = 1:17, ...) {
...
 
-.espn_week_checkmax <- function(conn) {
-  url_query <- glue::glue(
-    "https://fantasy.espn.com/apis/v3/games/ffl/seasons/",
-    "{conn$season}/segments/0/leagues/{conn$league_id}",
-    "?scoringPeriodId=0&view=mSettings"
-  )
-
-  settings <- espn_getendpoint_raw(conn, url_query)
+.espn_week_checkmax <- function(settings) {
```
Comment (tonyelhabr) [inline R/espn_starters.R:89]: took the leisure of editing this function to take in the `settings` list instead of the raw connection. the proposed `.espn_week_matchup_periods_mapping()` also needs elements in the settings list. This refactor avoids hitting the settings endpoint more than once.

File: R/espn_starters.R [hunk 2]
```diff
@@ -87,19 +99,44 @@ ff_starters.espn_conn <- function(conn, weeks = 1:17, ...) {
   return(max_week)
 }
 
-.espn_week_starter <- function(week, conn) {
+.espn_week_matchup_periods_mapping <- function(settings) {
+
+  matchup_periods <- settings %>%
+    purrr::pluck("content", "settings", "scheduleSettings", "matchupPeriods")
+
+  ## first, flatten out the values.
```
Comment (tonyelhabr) [inline R/espn_starters.R:107]: raw nested values look like this

```
$`16`[[1]]
[1] 17

$`16`[[2]]
[1] 18
```

it's easier to work with when it's like this

```
$`16`
[1] 17 18
```

File: R/espn_starters.R [hunk 3]
```diff
@@ -87,19 +99,44 @@ ff_starters.espn_conn <- function(conn, weeks = 1:17, ...) {
...
+  mapping <- matchup_periods %>%
+    purrr::map(
+      function(.x) {
+        unlist(.x)
+      }
+    )
+
+  ## then, invert the mapping such that the NFL week is the name and the matchupPeriod
+  ##   (whic is always <= NFL week) is the value.
+  inverted_mapping <- list()
```
Comment (tonyelhabr) [inline R/espn_starters.R:117]: and this converts this

```r
$`16`
[1] 17 18
```

to

```
$`17`
[1] 16

$`18`
[1] 16
```

**Comment by tonyelhabr** [comment]
> Looks good, thanks for the comment details! Can you add a test case that covers this, and ensure it runs if you have the MOCK_BYPASS envvar set?

Just pushed a change! Let me know if I've done it correctly. I think I may need to add data to the cache ZIP in the `tests-devel` release, although I'm not totally sure. (I haven't used `httptest` before 🤷 .)

**Comment by tanho63** [comment]
> I think I may need to add data to the cache ZIP in the tests-devel release, although I'm not totally sure. (I haven't used httptest before 🤷 .)

Unsure if you've permissions to, I was trying to figure out the best way to do that

**Review by tanho63 — APPROVED** [review]
LGTM, I think I did the thing backend that should make tests-devel.zip work again...

**Comment by tonyelhabr** [comment]
> LGTM, I think I did the thing backend that should make tests-devel.zip work again...

🥳
